In [1]:
import os
import numpy as np
import random
import pickle
import sys

from models_config.model_config_GSP import *
from utils.analysis import *
from utils.config import SAVE_DIR_DATA
from utils.simualte_data import simulate_data
from main_cross_validation import parrallel_run_A
from main_rep_kd import parrallel_run_B
from main_vanilla_kd import parrallel_run_vanilla_kd
from main_fitnet import parrallel_run_fitnet
from main_lsp import parrallel_run_lsp
from main_mskd import parrallel_run_mskd

# 1. Create Demo Dataset

In [2]:
print("Creating demo dataset...")
subjects = 10
nodes = 35
views = 6

mu_0 = 3
sigma_0 = 0.2
mu_1 = 2.8
sigma_1 = 0.3

adjs_0 = simulate_data(subjects, nodes, views, sigma_0, mu_0)
adjs_1 = simulate_data(subjects, nodes, views, sigma_1, mu_1)

adjs = adjs_0 + adjs_1

labels = [0] * subjects + [1] * subjects
if not os.path.exists(SAVE_DIR_DATA + "gender_data"):
    os.makedirs(SAVE_DIR_DATA + "gender_data") 

with open(SAVE_DIR_DATA+'gender_data/gender_data_edges', 'wb') as f:
    pickle.dump(adjs, f)

with open(SAVE_DIR_DATA+'gender_data/gender_data_labels', 'wb') as f:
    pickle.dump(labels, f)
print("Finished creating demo dataset")


Creating demo dataset...
Finished creating demo dataset


# 2. Train teacher model and student model

In [3]:
print("Pre-training teacher model and student model...")
run = 0
parrallel_run_A(run, "gender_data")
print("Finished Pre-training teacher model and student model")

Pre-training teacher model and student model...
/Users/lorenzostigliano/Documents/University/Imperial/TEST/thesis-imperial/model_data/gender_data/gcn/model_assessment/gcn
Run : 0
--------------------------------------------------------------------------
Main :  0 MainModel_3Fold_gender_data_gcn_run_0_fixed_init 3
CV :  0
Num training graphs:  14 ; Num test graphs:  6
Size of Training Set: 14
Size of Validation Set: 6
---------------------------------
Time taken for epoch 0: 0.03220963478088379
Train accuracy: 0.7857142857142857
Train loss: 0.43591800332069397
GCN Weights are saved:
Parameter containing:
tensor([[ 0.1638,  0.1411,  0.1548, -0.0570, -0.0576, -0.0181,  0.0503,  0.0692,
         -0.0148, -0.1093, -0.1276,  0.1633, -0.0456, -0.0216, -0.1038, -0.0839,
          0.0369,  0.0711, -0.0665, -0.0623,  0.1346, -0.0869, -0.1252, -0.0256,
          0.1607,  0.0364,  0.0235, -0.0208,  0.1055, -0.0838,  0.1143,  0.0405,
          0.0200,  0.0230, -0.1041]], requires_grad=True)
Validat

/Users/lorenzostigliano/Documents/University/Imperial/env-test/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Size of Training Set: 16
Size of Validation Set: 4
---------------------------------
Time taken for epoch 0: 0.029437780380249023
Train accuracy: 0.75
Train loss: 0.510094404220581
GCN Weights are saved:
Parameter containing:
tensor([[ 0.1637,  0.1405,  0.1536, -0.0570, -0.0578, -0.0182,  0.0500,  0.0687,
         -0.0151, -0.1093, -0.1277,  0.1630, -0.0457, -0.0225, -0.1038, -0.0840,
          0.0369,  0.0712, -0.0668, -0.0623,  0.1343, -0.0871, -0.1259, -0.0262,
          0.1607,  0.0364,  0.0235, -0.0211,  0.1055, -0.0839,  0.1143,  0.0402,
          0.0196,  0.0230, -0.1043]], requires_grad=True)
Validation accuracy: 1.0
Validation Loss: 0.33402828499674797
Average Memory Usage: 268.78125 MB, Std: 0.0
Average Time: 0.029437780380249023, Std: 0.0
CV :  4
Num training graphs:  16 ; Num test graphs:  4
Size of Training Set: 16
Size of Validation Set: 4
---------------------------------
Time taken for epoch 0: 0.026720285415649414
Train accuracy: 0.8125
Train loss: 0.4982491433620453
G

/Users/lorenzostigliano/Documents/University/Imperial/env-test/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/lorenzostigliano/Documents/University/Imperial/env-test/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/lorenzostigliano/Documents/University/Imperial/env-test/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier

---------------------------------
Time taken for epoch 0: 0.03692030906677246
Train accuracy: 0.7777777777777778
Train loss: 0.47497034072875977
GCN Weights are saved:
Parameter containing:
tensor([[ 0.1636,  0.1407,  0.1540, -0.0568, -0.0579, -0.0178,  0.0500,  0.0690,
         -0.0148, -0.1091, -0.1274,  0.1633, -0.0457, -0.0224, -0.1039, -0.0840,
          0.0368,  0.0709, -0.0667, -0.0623,  0.1343, -0.0871, -0.1251, -0.0260,
          0.1607,  0.0365,  0.0239, -0.0210,  0.1056, -0.0838,  0.1143,  0.0403,
          0.0199,  0.0235, -0.1043]], requires_grad=True)
Validation accuracy: 1.0
Validation Loss: 0.3620181530714035
Average Memory Usage: 266.26953125 MB, Std: 0.0
Average Time: 0.03692030906677246, Std: 0.0
CV :  6
Num training graphs:  18 ; Num test graphs:  2
Size of Training Set: 18
Size of Validation Set: 2
---------------------------------
Time taken for epoch 0: 0.03201651573181152
Train accuracy: 0.7777777777777778
Train loss: 0.480864942073822
GCN Weights are saved:
Par

/Users/lorenzostigliano/Documents/University/Imperial/env-test/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/lorenzostigliano/Documents/University/Imperial/env-test/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Size of Training Set: 18
Size of Validation Set: 2
---------------------------------
Time taken for epoch 0: 0.021912813186645508
Train accuracy: 0.4444444444444444
Train loss: 0.7050116062164307
GCN Weights are saved:
Parameter containing:
tensor([[ 0.0659,  0.1398,  0.1471,  0.1497,  0.0328, -0.1478,  0.0147, -0.1064,
         -0.1585,  0.1495,  0.1280, -0.1689,  0.0316, -0.0296, -0.0279, -0.0779,
          0.0649, -0.1003,  0.0613,  0.0845,  0.1206,  0.0630, -0.1673, -0.1102,
          0.0837,  0.0349, -0.1326, -0.0979,  0.1586,  0.1133, -0.0748, -0.0424,
         -0.1615, -0.0030, -0.1269]], requires_grad=True)
Validation accuracy: 0.5
Validation Loss: 0.7401935458183289
Average Memory Usage: 265.03125 MB, Std: 0.0
Average Time: 0.021912813186645508, Std: 0.0
CV :  4
Num training graphs:  18 ; Num test graphs:  2
Size of Training Set: 18
Size of Validation Set: 2
---------------------------------
Time taken for epoch 0: 0.02493119239807129
Train accuracy: 0.3888888888888889
Train l

# 3. Train RepKD

In [4]:
print("Training RepKD...")
parrallel_run_B(run, "gender_data")
print("Finished RepKD...")

Training RepKD...
0
/Users/lorenzostigliano/Documents/University/Imperial/TEST/thesis-imperial/model_data/gender_data/gcn/model_assessment/gcn_student_lsp_ensamble_2
Run :  0
--------------------------------------------------------------------------
Main :  0 MainModel_3Fold_gender_data_gcn_student_lsp_ensamble_2_run_0_fixed_init 3
Num training graphs:  14 ; Num test graphs:  6
CV : 0
Size of Training Set: 14
Size of Validation Set: 6
---------------------------------
Time taken for epoch 0: 0.16232800483703613
Train total loss: 2.3879184212003435
Train teacher and student loss: 0.6941686187471662
Train within student loss for weights: 0.13383997870343073
GCN Weights are saved:
Parameter containing:
tensor([[ 0.0670,  0.1409,  0.1478,  0.1478,  0.0326, -0.1480,  0.0164, -0.1045,
         -0.1588,  0.1488,  0.1279, -0.1700,  0.0329, -0.0273, -0.0269, -0.0780,
          0.0638, -0.1003,  0.0613,  0.0852,  0.1203,  0.0632, -0.1664, -0.1083,
          0.0856,  0.0342, -0.1309, -0.0967,  0.

## Getting the best model for RepKD

In [5]:
analysis_type="model_assessment"
dataset_split="val"
dataset="gender_data"
models_args=[
    gcn_student_lsp_ensamble_2_args,
    gcn_student_lsp_ensamble_3_args,
    gcn_student_lsp_ensamble_4_args,
    gcn_student_lsp_ensamble_5_args
]
views = [0]

#GET ALL OF THE MODEL BEST STUDENTS FOR ALL RUNS AND DIFFERENT PICKING CRITERIA FOR OUR MODEL 
all_model_metrics_mean, all_model_metrics_var, all_model_best_student = get_all_best_student(analysis_type, dataset_split, dataset, models_args, views)

gcn_student_lsp_ensamble_2
[[1.0, 0.0, 0], [0.9833333333333334, 0.0, 1], [1.0, 0.0, 0], [1.0, 0.0, 0], [1.0, 0.0, 0]]
gcn_student_lsp_ensamble_3
[[1.0, 0.0, 0], [1.0, 0.0, 2], [1.0, 0.0, 2], [1.0, 0.0, 2], [1.0, 0.0, 2]]
gcn_student_lsp_ensamble_4
[[1.0, 0.0, 0], [1.0, 0.0, 2], [1.0, 0.0, 2], [1.0, 0.0, 2], [1.0, 0.0, 2]]
gcn_student_lsp_ensamble_5
[[1.0, 0.0, 0], [1.0, 0.0, 4], [1.0, 0.0, 2], [1.0, 0.0, 4], [1.0, 0.0, 2]]


In [6]:
df_rep, df_acuracy, _, index = final_student(all_model_metrics_mean, all_model_metrics_var, all_model_best_student, selection_method='weighted acc')

In [7]:
# Self-reproduciblity score of the best student in each ensemble
# x-axis: number of students in ensemble (2, 3, 4, 5)
# y-axis: view (data)
df_rep

2    3    4    5
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0

In [8]:
# Accuracy of perforemance of the best student in each ensemble
df_acuracy

2    3    4         5
0  0.438889  0.5  0.5  0.603704
1  0.438889  0.5  0.5  0.603704

In [9]:
# Index of the best student in each ensemble
index

2    3    4    5
0  0.0  2.0  2.0  4.0

# Comparison with baselines

In [10]:
print("Training using vanilla KD")
run = 0
parrallel_run_vanilla_kd(run, "gender_data")
print("Finished using vanilla KD")

Training using vanilla KD
0
/Users/lorenzostigliano/Documents/University/Imperial/TEST/thesis-imperial/model_data/gender_data/gcn/model_assessment/gcn_student
Run :  0
--------------------------------------------------------------------------
Main :  0 MainModel_3Fold_gender_data_gcn_student_run_0_fixed_init 3
Num training graphs:  14 ; Num test graphs:  6
CV : 0
MainModel_3Fold_gender_data_gcn_student_run_0_fixed_init_CV_0_view_0_with_teacher
Size of Training Set: 14
Size of Validation Set: 6
---------------------------------
Time taken for epoch 0: 0.03463411331176758
Train accuracy: 0.35714285714285715
Train loss: 1.420444437435695
Train Soft CE loss: 0.6994999817439488
Train CE loss: 0.7209444429193225
GCN Weights are saved:
Parameter containing:
tensor([[ 0.0655,  0.1398,  0.1472,  0.1494,  0.0328, -0.1473,  0.0145, -0.1058,
         -0.1577,  0.1499,  0.1284, -0.1682,  0.0316, -0.0286, -0.0277, -0.0771,
          0.0651, -0.1004,  0.0618,  0.0847,  0.1209,  0.0632, -0.1668, -0.10

In [11]:
print("Training using fitnet")
run = 0
parrallel_run_fitnet(run, "gender_data")
print("Finished using fitnet")

Training using fitnet
0
/Users/lorenzostigliano/Documents/University/Imperial/TEST/thesis-imperial/model_data/gender_data/gcn/model_assessment/fitnet
Run :  0
--------------------------------------------------------------------------
Main :  0 MainModel_3Fold_gender_data_fitnet_run_0_fixed_init 3
Num training graphs:  14 ; Num test graphs:  6
CV : 0
MainModel_3Fold_gender_data_fitnet_run_0_fixed_init_CV_0_view_0_fitnet
Size of Training Set: 14
Size of Validation Set: 6
---------------------------------
Time taken for epoch 0: 0.04365205764770508
Train accuracy: 0.35714285714285715
Train loss: 1.7213233198438371
Train Soft CE loss: 0.6996975753988538
Train CE loss: 0.7206846475601196
Train MSE loss: 1.504705433334623
GCN Weights are saved:
Parameter containing:
tensor([[ 0.0575,  0.1378,  0.1485,  0.1517,  0.0257, -0.1498,  0.0055, -0.1067,
         -0.1595,  0.1469,  0.1275, -0.1639,  0.0310, -0.0300, -0.0266, -0.0742,
          0.0660, -0.1026,  0.0602,  0.0781,  0.1197,  0.0631, -0.1

In [12]:
print("Training using lsp")
run = 0
parrallel_run_lsp(run, "gender_data")
print("Finished using lsp")

Training using lsp
0
/Users/lorenzostigliano/Documents/University/Imperial/TEST/thesis-imperial/model_data/gender_data/gcn/model_assessment/lsp
Run :  0
--------------------------------------------------------------------------
Main :  0 MainModel_3Fold_gender_data_lsp_run_0_fixed_init 3
Num training graphs:  14 ; Num test graphs:  6
CV : 0
MainModel_3Fold_gender_data_lsp_run_0_fixed_init_CV_0_view_0_lsp
Size of Training Set: 14
Size of Validation Set: 6
---------------------------------
Time taken for epoch 0: 0.14357376098632812
Train accuracy: 0.35714285714285715
Train loss: 0.887320910181318
Train KD loss: 0.08233010955154896
Train CE loss: 0.7226606948035104
GCN Weights are saved:
Parameter containing:
tensor([[ 0.0575,  0.1378,  0.1489,  0.1517,  0.0258, -0.1498,  0.0054, -0.1067,
         -0.1595,  0.1470,  0.1275, -0.1639,  0.0312, -0.0299, -0.0264, -0.0742,
          0.0661, -0.1025,  0.0604,  0.0782,  0.1201,  0.0635, -0.1622, -0.1090,
          0.0805,  0.0316, -0.1306, -0.0

In [13]:
print("Training using mskd")
run = 0
parrallel_run_mskd(run, "gender_data")
print("Finished using mskd")

Training using mskd
0
/Users/lorenzostigliano/Documents/University/Imperial/TEST/thesis-imperial/model_data/gender_data/gcn/model_assessment/mskd
Run :  0
--------------------------------------------------------------------------
Main :  0 MainModel_3Fold_gender_data_mskd_run_0_fixed_init 3
Num training graphs:  14 ; Num test graphs:  6
CV : 0
MainModel_3Fold_gender_data_mskd_run_0_fixed_init_CV_0_view_0_mskd
Size of Training Set: 14
Size of Validation Set: 6
---------------------------------
Time taken for epoch 0: 0.25550007820129395
Train accuracy: 0.35714285714285715
Train loss: 3.6038959196635654
Train MSKD loss: 8.528335021042364e-07
Train CE loss: 0.7225370981863567
GCN Weights are saved:
Parameter containing:
tensor([[ 0.0575,  0.1375,  0.1480,  0.1514,  0.0254, -0.1500,  0.0054, -0.1068,
         -0.1598,  0.1467,  0.1274, -0.1640,  0.0308, -0.0302, -0.0269, -0.0746,
          0.0651, -0.1030,  0.0597,  0.0780,  0.1191,  0.0628, -0.1630, -0.1101,
          0.0797,  0.0314, -0.

# 4. Compare our method with the baselines

## 4.a. Get reproduciblity scores

In [14]:
#GET THE REPRODUCIBILITY SCORE FOR ALL MODELS 
mean_all_runs, mean_all_std = reproducibility_mulitple_runs_student_specific(
    dataset="gender_data", 
    views=[0], 
    models=[  
        "gcn", 
        "gcn_student",
        "gcn_student_teacher",
        "fitnet", 
        "lsp", 
        "mskd",
        "gcn_student_lsp_ensamble_4" 
    ], 
    CV=["3Fold", "5Fold", "10Fold"], 
    runs=[i for i in range(1)], 
    students=[
        [1]
    ], 
    model_args= [
        gcn_args,
        gcn_student_args,
        gcn_student_args, 
        gcn_fitnet_student_args, 
        gcn_lsp_student_args, 
        gcn_mskd_student_args,
        gcn_student_lsp_ensamble_4_args
    ])

In [15]:
import pandas as pd

reproducibility_frame = pd.DataFrame(mean_all_runs.T)

In [16]:
models=["gcn", "gcn_student", "gcn_student_teacher", "fitnet_gcn", "lsp_gcn", "mskd_gcn", "repKD"]
reproducibility_frame.columns = models
reproducibility_frame = reproducibility_frame*100

reproducibility_frame.T

0           1
gcn                  100.000000  100.000000
gcn_student          100.000000  100.000000
gcn_student_teacher  100.000000  100.000000
fitnet_gcn            96.388889   96.388889
lsp_gcn               97.222222   97.222222
mskd_gcn              97.222222   97.222222
repKD                100.000000  100.000000

In [17]:
reproducibility_frame_std = pd.DataFrame(mean_all_std.T)*100
models=["gcn", "gcn_student", "gcn_student_teacher", "fitnet_gcn", "lsp_gcn", "mskd_gcn", "repKD"]
reproducibility_frame_std.columns = models
reproducibility_frame_std.T

0    1
gcn                  0.0  0.0
gcn_student          0.0  0.0
gcn_student_teacher  0.0  0.0
fitnet_gcn           0.0  0.0
lsp_gcn              0.0  0.0
mskd_gcn             0.0  0.0
repKD                0.0  0.0

## 4.b. Get performance metrics

In [18]:
views=[0]
CV=["3Fold", "5Fold", "10Fold"]

runs = [i for i in range(1)]
dataset = "gender_data"
dataset_split="val"
analysis_type="model_assessment"
metrics = ["acc"]

final_model = ["gcn_student_lsp_ensamble_4"]
final_model_args = [gcn_student_lsp_ensamble_4_args]
best_student = [1]
baseline_models = ["gcn", "gcn_student", "gcn_student_teacher", "fitnet", "lsp", "mskd"]
baseline_models_args = [
    gcn_args,
    gcn_student_args,
    gcn_student_args, 
    gcn_fitnet_student_args, 
    gcn_lsp_student_args, 
    gcn_mskd_student_args
]

In [19]:
average_across_views_df, average_across_views_df_std_mean = performance_mulitple_runs_student_specific(final_model, final_model_args, best_student, baseline_models, baseline_models_args, views, CV, runs, dataset, dataset_split, analysis_type, metrics)

In [20]:
average_across_views_df = pd.DataFrame(average_across_views_df)
models=["gcn", "gcn_student", "gcn_student_teacher", "fitnet", "lsp", "mskd", "repKD"]

average_across_views_df.columns = models
average_across_views_df = average_across_views_df*100
average_across_views_df.T

0          1
gcn                  84.444444  84.444444
gcn_student          43.888889  43.888889
gcn_student_teacher  43.888889  43.888889
fitnet               44.074074  44.074074
lsp                  50.740741  50.740741
mskd                 54.074074  54.074074
repKD                44.814815  44.814815

In [21]:
average_across_views_df_std_mean = pd.DataFrame(average_across_views_df_std_mean)
models=["gcn", "gcn_student", "gcn_student_teacher", "fitnet", "lsp", "mskd", "repKD"]

average_across_views_df_std_mean.columns = models
average_across_views_df_std_mean.T*100

0
gcn                  0.0
gcn_student          0.0
gcn_student_teacher  0.0
fitnet               0.0
lsp                  0.0
mskd                 0.0
repKD                0.0